/Library/Python/3.8/site-packages/celery/backends/amqp.py:65: CPendingDeprecationWarning: 
    The AMQP result backend is scheduled for deprecation in     version 4.0 and removal in version v5.0.     Please use RPC backend or a persistent backend.

  deprecated.warn(
[2021-07-05 16:37:09,602: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:09,616: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:09,628: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:09,641: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:09,654: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:09,668: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:09,668: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:10,701: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:10,715: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:10,728: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:10,743: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:10,758: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:10,773: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:10,774: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:11,798: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:11,813: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:11,826: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:11,839: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:11,852: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:11,866: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:11,866: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:12,891: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:12,906: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:12,921: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:12,936: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:12,951: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:12,965: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:12,966: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:13,989: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:14,004: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:14,017: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:14,031: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:14,044: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:14,057: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:14,058: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:15,085: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:15,104: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:15,120: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:15,134: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:15,148: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:15,162: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:15,162: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:16,185: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:16,201: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:16,216: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:16,230: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:16,242: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:16,256: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:16,256: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:17,279: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:17,293: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:17,305: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:17,327: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:17,342: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:17,355: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:17,355: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:18,380: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:18,396: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:18,412: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:18,427: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:18,442: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:18,458: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:18,458: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:19,477: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:19,491: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:19,505: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:19,518: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:19,531: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:19,544: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:19,544: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:20,567: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:20,581: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:20,593: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:20,606: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:20,619: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:20,633: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:20,633: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:21,657: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:21,672: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:21,686: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:21,700: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:21,714: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:21,729: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:21,729: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:22,752: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:22,767: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:22,781: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:22,795: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:22,809: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:22,822: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:22,822: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:23,847: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:23,860: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:23,873: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:23,885: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:23,900: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:23,916: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:23,916: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:24,940: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:24,955: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:24,969: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:24,984: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:24,999: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:25,013: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:25,014: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:26,040: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:26,055: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:26,069: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:26,083: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:26,097: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:26,112: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:26,112: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:27,139: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:27,156: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:27,173: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:27,189: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:27,205: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:27,221: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:27,222: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:28,243: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:28,257: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:28,270: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:28,284: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:28,298: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:28,311: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:28,312: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:29,335: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:29,349: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:29,361: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:29,374: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:29,387: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:29,400: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:29,400: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:30,425: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:30,440: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:30,453: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:30,466: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:30,479: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:30,496: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:30,496: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:31,519: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:31,533: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:31,546: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:31,559: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:31,573: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:31,586: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:31,586: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:32,610: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:32,624: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:32,638: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:32,655: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:32,671: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:32,688: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:32,688: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:33,712: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:33,725: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:33,737: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:33,751: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:33,765: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:33,778: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:33,778: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:34,803: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:34,818: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:34,835: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:34,851: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:34,867: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:34,883: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:34,884: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:35,909: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:35,924: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:35,938: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:35,951: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:35,963: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:35,976: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:35,977: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:36,999: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:37,012: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:37,024: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:37,037: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:37,051: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:37,065: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:37,065: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:38,088: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:38,103: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:38,117: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:38,131: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:38,145: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:38,160: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:38,160: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:39,182: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:39,195: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:39,209: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:39,223: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:39,237: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:39,251: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:39,251: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:40,277: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:40,292: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:40,305: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:40,317: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:40,331: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:40,343: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:40,344: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:41,364: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:41,377: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:41,389: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:41,401: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:41,413: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:41,425: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:41,425: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:42,447: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:42,460: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:42,472: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:42,486: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:42,500: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:42,513: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:42,513: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:43,537: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:43,550: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:43,563: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:43,576: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:43,589: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:43,603: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:43,603: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:44,624: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:44,640: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:44,655: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:44,669: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:44,685: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:44,699: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:44,700: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:45,722: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:45,736: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:45,750: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:45,763: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:45,776: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:45,788: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:45,788: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:46,809: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:46,823: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:46,836: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:46,849: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:46,862: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:46,876: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:46,876: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:47,899: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:47,914: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:47,929: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:47,943: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:47,957: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:47,970: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:47,971: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
[2021-07-05 16:37:48,988: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:49,003: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:49,017: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:49,029: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:49,043: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:49,056: ERROR/MainProcess] consumer: Cannot connect to amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker: Connection.open: (530) NOT_ALLOWED - vhost unicorn_broker not found.
Trying to reconnect...

[2021-07-05 16:37:49,056: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/Library/Python/3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/Library/Python/3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)

worker: Cold shutdown (MainProcess)

worker: Cold shutdown (MainProcess)
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/util.py", line 201, in __call__
  File "/Library/Python/3.8/site-packages/billiard/heap.py", line 233, in free
AttributeError: 'NoneType' object has no attribute 'getpid'
 
 -------------- celery@amass_1 v4.4.7 (cliffs)
--- ***** ----- 
-- ******* ---- macOS-11.2.3-x86_64-i386-64bit 2021-07-05 16:37:09
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         hhsrc.amass:0x10c5c07f0
- ** ---------- .> transport:   amqp://hhsrc:**@127.0.0.1:5672/unicorn_broker
- ** ---------- .> results:     amqp://
- *** --- * --- .> concurrency: 1 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> amass            exchange=amass(direct) key=amass
                

[tasks]
  . amass.run

/Library/Python/3.8/site-packages/celery/backends/amqp.py:65: CPendingDeprecationWarning: 
    The AMQP result backend is scheduled for deprecation in     version 4.0 and removal in version v5.0.     Please use RPC backend or a persistent backend.

  deprecated.warn(
[2021-07-07 13:12:28,318: INFO/MainProcess] Connected to amqp://hhsrc:**@127.0.0.1:5672/hhsrc_broker
[2021-07-07 13:12:28,361: INFO/MainProcess] mingle: searching for neighbors
[2021-07-07 13:12:29,454: INFO/MainProcess] mingle: all alone
[2021-07-07 13:12:29,500: INFO/MainProcess] celery@amass_1625634746.948791 ready.
[2021-07-07 13:12:34,291: INFO/MainProcess] Events of group {task} enabled by remote.
/Library/Python/3.8/site-packages/celery/backends/amqp.py:65: CPendingDeprecationWarning: 
    The AMQP result backend is scheduled for deprecation in     version 4.0 and removal in version v5.0.     Please use RPC backend or a persistent backend.

  deprecated.warn(
[2021-07-07 13:14:00,263: INFO/MainProcess] Connected to amqp://hhsrc:**@127.0.0.1:5672/hhsrc_broker
[2021-07-07 13:14:00,300: INFO/MainProcess] mingle: searching for neighbors
[2021-07-07 13:14:01,371: INFO/MainProcess] mingle: all alone
[2021-07-07 13:14:01,427: INFO/MainProcess] celery@amass_1625634839.330644 ready.
[2021-07-07 13:14:06,251: INFO/MainProcess] Events of group {task} enabled by remote.
/Library/Python/3.8/site-packages/celery/backends/amqp.py:65: CPendingDeprecationWarning: 
    The AMQP result backend is scheduled for deprecation in     version 4.0 and removal in version v5.0.     Please use RPC backend or a persistent backend.

  deprecated.warn(
[2021-07-07 13:14:40,063: INFO/MainProcess] Connected to amqp://hhsrc:**@127.0.0.1:5672/hhsrc_broker
[2021-07-07 13:14:40,152: INFO/MainProcess] mingle: searching for neighbors
[2021-07-07 13:14:41,284: INFO/MainProcess] mingle: all alone
[2021-07-07 13:14:41,344: INFO/MainProcess] celery@amass_1625634878.3006752 ready.
[2021-07-07 13:14:46,012: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-07-07 13:16:00,014: INFO/MainProcess] Received task: amass.run[e4078a28-b33a-4521-a9e7-84a77ccbd2c7]  
vds.vivo.com
vivo.com
asia-expweb.vivo.com
sg-exstpay.vivo.com
asia-ali-cname-www.vivo.com
domaincfg.vivo.com
zs.vivo.com
mshop.vivo.com
shop.vivo.com
es.vivo.com
th-passport.vivo.com
bs.vivo.com
as.vivo.com
hr.vivo.com
zhaopin.vivo.com
devissue.vivo.com
identity.vivo.com
pc.vivo.com
asia-exstatic-vivofs.vivo.com
asia-exstatic.vivo.com
faq.vivo.com
mshopstatic-in.vivo.com
/Library/Python/3.8/site-packages/celery/backends/amqp.py:65: CPendingDeprecationWarning: 
    The AMQP result backend is scheduled for deprecation in     version 4.0 and removal in version v5.0.     Please use RPC backend or a persistent backend.

  deprecated.warn(
[2021-07-07 13:17:51,136: INFO/ForkPoolWorker-1] Task amass.run[e4078a28-b33a-4521-a9e7-84a77ccbd2c7] succeeded in 111.116217011s: {'tool': 'amass', 'result': ['vds.vivo.com', 'vivo.com', 'asia-expweb.vivo.com', 'sg-exstpay.vivo.com', 'asia-ali-cname-www.vivo.com', 'domaincfg.vivo.com', 'zs.vivo.com', 'mshop.vivo.com', 'shop.vivo.com', 'es.vivo.com', 'th-passport.vivo.com', 'bs.vivo.com', 'as.vivo.com', 'hr.vivo.com', 'zhaopin.vivo.com', 'devissue.vivo.com', 'identity.vivo.com', 'pc.vivo.com', 'asia-exstatic-vivofs.vivo.com', 'asia-exstatic.vivo.com', 'faq.vivo.com', 'mshopstatic-in.vivo.com']}
[2021-07-07 13:20:05,992: INFO/MainProcess] Received task: amass.run[21e8369d-a3ce-4945-aed6-06e4c3ae54e1]  
vivo.com
zs.vivo.com
mshopstatic-in.vivo.com
asia-exstatic.vivo.com
hr.vivo.com
zhaopin.vivo.com
faq.vivo.com
th-passport.vivo.com
vsin.vivo.com
mshop.vivo.com
as.vivo.com
www.vivo.com
developer.vivo.com
bs.vivo.com
shop.vivo.com
es.vivo.com
passport.vivo.com
devissue.vivo.com
homepage.vivo.com
asia-exstatic-vivofs.vivo.com
[2021-07-07 13:22:16,040: INFO/ForkPoolWorker-1] Task amass.run[21e8369d-a3ce-4945-aed6-06e4c3ae54e1] succeeded in 130.043170735s: {'tool': 'amass', 'result': ['vivo.com', 'zs.vivo.com', 'mshopstatic-in.vivo.com', 'asia-exstatic.vivo.com', 'hr.vivo.com', 'zhaopin.vivo.com', 'faq.vivo.com', 'th-passport.vivo.com', 'vsin.vivo.com', 'mshop.vivo.com', 'as.vivo.com', 'www.vivo.com', 'developer.vivo.com', 'bs.vivo.com', 'shop.vivo.com', 'es.vivo.com', 'passport.vivo.com', 'devissue.vivo.com', 'homepage.vivo.com', 'asia-exstatic-vivofs.vivo.com']}
/Library/Python/3.8/site-packages/celery/backends/amqp.py:65: CPendingDeprecationWarning: 
    The AMQP result backend is scheduled for deprecation in     version 4.0 and removal in version v5.0.     Please use RPC backend or a persistent backend.

  deprecated.warn(
[2021-07-07 13:45:39,660: INFO/MainProcess] Connected to amqp://hhsrc:**@127.0.0.1:5672/hhsrc_broker
[2021-07-07 13:45:39,701: INFO/MainProcess] mingle: searching for neighbors
[2021-07-07 13:45:40,776: INFO/MainProcess] mingle: all alone
[2021-07-07 13:45:40,834: INFO/MainProcess] celery@amass_1625636738.182301 ready.
[2021-07-07 13:45:46,179: INFO/MainProcess] Events of group {task} enabled by remote.
/Library/Python/3.8/site-packages/celery/backends/amqp.py:65: CPendingDeprecationWarning: 
    The AMQP result backend is scheduled for deprecation in     version 4.0 and removal in version v5.0.     Please use RPC backend or a persistent backend.

  deprecated.warn(
[2021-07-07 14:49:56,552: INFO/MainProcess] Connected to amqp://hhsrc:**@127.0.0.1:5672/hhsrc_broker
[2021-07-07 14:49:56,625: INFO/MainProcess] mingle: searching for neighbors
[2021-07-07 14:49:57,831: INFO/MainProcess] mingle: all alone
[2021-07-07 14:49:57,948: INFO/MainProcess] celery@amass_1625640593.531957 ready.
[2021-07-07 14:50:02,419: INFO/MainProcess] Events of group {task} enabled by remote.
